name: workflow

on:
  push:
    branches:
      -main
    paths-ignore:
      "README.md"

permissions:
  id-token: write
  contents: read


jobs:
  integration:
  name: Continuous Integration
  runs-on: ubuntu-latest

  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Lint code
      uses: echo "running Linting repository"
      
    - name: Run unit tests
      uses: echo "Running unit tests"